### ISSUE TITLE
Create a docker

### ISSUE THREAD

**Issue by StayerX** [project-renard/devops#34]
Create a docker for  project renard and document the most important and relevant steps.
- [X] docker image of curie with perl and the other components installed based on vagrant setup scripts.
- [ ]  X11 support
- [ ] See if possible to build automatically trhough apvayor and push to docker with encrypted keys. 
- [ ] Clean the docker image.
- [ ] Add Helen to docker.
- [ ] Create a script that auto updates the repositories.

**Comment by StayerX** [comment]
For X11: 
* https://forums.docker.com/t/how-to-display-gui-on-xming-from-a-docker-container/30498
* https://github.com/baudren/NoteOrganiser/wiki/Docker,-QML,-XServer-on-Windows
* http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container
* http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
* http://elijahcaine.me/blog/running-firefox-in-docker/
* https://manomarks.net/2015/12/03/docker-gui-windows.html

**Comment by zmughal** [comment]
Closing in favour of <https://github.com/oberth-manoeuvre/oberth-prototype>, <https://github.com/oberth-manoeuvre/oberth-prototype/issues/23>.
