### ISSUE TITLE
Create a small docker

### ISSUE THREAD

**Issue by StayerX** [project-renard/devops#37]
- [ ] Use the alpine docker as base.
- [ ] Do not add to the docker image the history and all the irrelevant directories.  
- [ ] Rename the docker repositories accordingly. For example curie to devops.

**Comment by zmughal** [comment]
Closing in favour of <https://github.com/oberth-manoeuvre/oberth-prototype/issues/19>, <https://github.com/oberth-manoeuvre/oberth-prototype/issues/22>.
