### ISSUE TITLE
Create an automatic installation/ packaging based on the distribution

### ISSUE THREAD

**Issue by StayerX** [project-renard/devops#5]
Something like this could be used as a starting point

```
#!/bin/bash
# Check if the platform is debian/ubuntu based or Redhat/CenOS (no support for the rest.. yet)
python -mplatform |egrep -i "Ubuntu|Debian" && debianbased=true||debianbased=false

if [ "$debianbased" = true ] ; then
    echo -n 'Assuming Debian based GNU/Linux,\nProceding with installation'
    sudo xargs apt-get install \
        -y --no-install-recommends \
        < debian-packages-vagrant
else
    echo -n 'Assuming RedHat based distribution'
    sudo xargs yum install \
        -y --no-install-recommends \
        < redhat-packages-vagran
 fi
```

**Comment by ChiragGhanshani** [comment]
I don't think it's a good idea to use the distribution package managers. There was a warning on the Vagrant website that they sometimes have incomplete vagrant/virtualbox packages. I think we should look into using wget to download the packages that are available online and then use the OS included unpacking utilities to install them.

**Comment by zmughal** [comment]
Which packages are we talking about? The dependencies of `curie` or the installation of the `vagrant` tool?

**Comment by StayerX** [comment]
I am thinking of the dependencies of curie as well as vagrant itself, and virtual box, on which vagrant  depends. And/or anything else that might come along.

**Comment by zmughal** [comment]
Closing in favour of <https://github.com/oberth-manoeuvre/oberth-prototype>. This is done by a YAML file.
